"""fact_demographics_by_nis_code_and_category

Revision ID: 508023bd0f42
Revises: 7965df23d97d
Create Date: 2021-11-15 11:00:13.301393

"""
from alembic import op
import sqlalchemy as sa

from app.utils import get_db_type


# revision identifiers, used by Alembic.
revision = "508023bd0f42"
down_revision = "7965df23d97d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_demographics_by_nis_code_and_category",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("nis", sa.String(5), nullable=False),
        sa.Column("sex", sa.String(5), nullable=False),
        sa.Column("nationality_code", sa.String(5), nullable=False),
        sa.Column("nationality_text_nl", sa.String(255), nullable=True),
        sa.Column("nationality_text_fr", sa.String(255), nullable=True),
        sa.Column("marital_status_code", sa.String(5), nullable=False),
        sa.Column("marital_status_text_nl", sa.String(255), nullable=True),
        sa.Column("marital_status_text_fr", sa.String(255), nullable=True),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        (sa.CheckConstraint("LEN(nis)=5"))
        if (get_db_type() == "mssql")
        else (sa.CheckConstraint("length(nis)==5")),
        sa.PrimaryKeyConstraint(
            "year", "nis", "sex", "nationality_code", "marital_status_code", "age"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_demographics_by_nis_code_and_category")
    # ### end Alembic commands ###
