"""etl_logs

Revision ID: 4463b6adbfd4
Revises: 52c236279c17
Create Date: 2021-11-19 09:17:33.522402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4463b6adbfd4'
down_revision = '52c236279c17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'etl_logs',
        sa.Column('_ID', sa.Integer(), nullable=False),
        sa.Column('module', sa.String(), nullable=True),
        sa.Column('filename', sa.String(), nullable=True),
        sa.Column('line', sa.Integer(), nullable=True),
        sa.Column('level', sa.String(), nullable=True),
        sa.Column('trace', sa.String(), nullable=True),
        sa.Column('message', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('etl_logs')
    # ### end Alembic commands ###
