"""fact_number_of_deaths_by_district_nis_code

Revision ID: d7fd1832e0dd
Revises: 508023bd0f42
Create Date: 2021-11-15 14:48:36.488220

"""
from alembic import op
import sqlalchemy as sa

from app.utils import get_db_type


# revision identifiers, used by Alembic.
revision = "d7fd1832e0dd"
down_revision = "508023bd0f42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_number_of_deaths_by_district_nis_code",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("nis_district", sa.String(5), nullable=False),
        sa.Column("sex", sa.String(5), nullable=False),
        sa.Column("agegroup", sa.String(32), nullable=False),
        sa.Column("number_of_deaths", sa.Integer(), nullable=False),
        (sa.CheckConstraint("LEN(nis_district)=5"))
        if (get_db_type() == "mssql")
        else (sa.CheckConstraint("length(nis_district)==5")),
        sa.PrimaryKeyConstraint("date", "nis_district", "sex", "agegroup"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_number_of_deaths_by_district_nis_code")
    # ### end Alembic commands ###
