"""fact_covid_confirmed_cases_by_category

Revision ID: 7965df23d97d
Revises: 11a7ec4e32c9
Create Date: 2021-11-15 00:03:52.454099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7965df23d97d"
down_revision = "11a7ec4e32c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_covid_confirmed_cases_by_category",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("province", sa.String(255), nullable=False),
        sa.Column("region", sa.String(255), nullable=False),
        sa.Column("agegroup", sa.String(32), nullable=False),
        sa.Column("sex", sa.String(5), nullable=False),
        sa.Column("cases", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date", "province", "region", "agegroup", "sex"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fact_covid_confirmed_cases_by_category")
    # ### end Alembic commands ###
