"""dim_nis_codes

Revision ID: 522d837cbaa1
Revises: c317ec5b7286
Create Date: 2021-11-14 23:22:50.991580

"""
from alembic import op
import sqlalchemy as sa

from app.utils import get_db_type


# revision identifiers, used by Alembic.
revision = "522d837cbaa1"
down_revision = "c317ec5b7286"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dim_nis_codes",
        sa.Column("nis", sa.String(length=5), nullable=False),
        sa.Column("parent_nis", sa.String(length=5), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("text_nl", sa.String(length=255), nullable=True),
        sa.Column("text_fr", sa.String(length=255), nullable=True),
        sa.Column("text_de", sa.String(length=255), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_till", sa.Date(), nullable=False),
        (sa.CheckConstraint("LEN(nis)=5"))
        if (get_db_type() == "mssql")
        else (sa.CheckConstraint("length(nis)==5")),
        (sa.CheckConstraint("LEN(parent_nis)=5"))
        if (get_db_type() == "mssql")
        else (sa.CheckConstraint("length(parent_nis)==5")),
        sa.PrimaryKeyConstraint("nis", "valid_from"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dim_nis_codes")
    # ### end Alembic commands ###
