"""'fact_vaccinations_by_nis_code_daily_updated' added 'vaccinated_with_booster'

Revision ID: 46deee2886a2
Revises: 4463b6adbfd4
Create Date: 2021-12-05 15:50:35.159470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46deee2886a2'
down_revision = '4463b6adbfd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fact_vaccinations_by_nis_code_daily_updated', sa.Column('vaccinated_with_booster', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fact_vaccinations_by_nis_code_daily_updated', 'vaccinated_with_booster')
    # ### end Alembic commands ###
